version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/rozzwork-admin
permissions:
  - object: /home/ec2-user/rozzwork-admin
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/docker-pull.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/docker-run.sh
      timeout: 300
      runas: root
